import 'dart:async';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import '../../config/app_config.dart';
import '../../services/api_service.dart';
import '../../services/tabu_game_api_service.dart';
import '../../services/tabu_realtime_service.dart';
import '../../theme/app_colors.dart';
import '../../widgets/brand.dart';

class TabuRoomScreen extends StatefulWidget {
  const TabuRoomScreen({super.key,required this.roomId,this.profileName=''});
  final String roomId; final String profileName;
  @override State<TabuRoomScreen> createState()=>_TabuRoomScreenState();
}
class _TabuRoomScreenState extends State<TabuRoomScreen>{
  final input=TextEditingController(); final scroll=ScrollController();
  StreamSubscription<TabuRealtimeEvent>? sub; Timer? clock; Map<String,dynamic>? state;
  bool loading=true,sending=false; String? error;
  static const navy=AppColors.navy,lime=AppColors.lime,coral=Color(0xFFFF5F68);
  bool get dark=>Theme.of(context).brightness==Brightness.dark;
  Color get page=>dark?const Color(0xFF071022):const Color(0xFFF8F9FD);
  Color get surface=>dark?const Color(0xFF111B2E):Colors.white;
  Color get surface2=>dark?const Color(0xFF172338):const Color(0xFFF0F1F5);
  Color get ink=>dark?const Color(0xFFF5F7FF):navy;
  Color get muted=>dark?const Color(0xFFAAB5CA):const Color(0xFF7F8598);
  Color get line=>dark?const Color(0xFF29364D):const Color(0xFFE7E9F0);
  @override void initState(){super.initState();input.addListener(_changed);_connect();clock=Timer.periodic(const Duration(seconds:1),(_){if(mounted)setState((){});});}
  void _changed(){if(mounted)setState((){});}
  @override void dispose(){sub?.cancel();clock?.cancel();input.removeListener(_changed);input.dispose();scroll.dispose();super.dispose();}
  Map<String,dynamic>? _stateFrom(Map<String,dynamic>d){final r=d['state'];if(r is Map)return Map<String,dynamic>.from(r);if(d['game']?.toString()=='tabu')return d;return null;}
  List<Map<String,dynamic>> _maps(dynamic r)=>r is List?r.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList():const[];
  List<Map<String,dynamic>> _messages(Map<String,dynamic>?s)=>_maps(s?['messages']);
  int _secondsLeft(String key){final e=DateTime.tryParse(state?[key]?.toString()??'');if(e==null)return 0;final ms=e.difference(DateTime.now()).inMilliseconds;return ms<=0?0:math.min(999,(ms/1000).ceil());}
  String _photo(Map<String,dynamic>p){final r=p['photoUrl']?.toString().trim()??'';if(r.isEmpty)return'';final u=Uri.tryParse(r);if(u!=null&&u.hasScheme)return r;return '${AppConfig.apiBaseUrl}${r.startsWith('/')?r:'/$r'}';}
  void _scrollSoon(){WidgetsBinding.instance.addPostFrameCallback((_){if(scroll.hasClients)scroll.animateTo(scroll.position.maxScrollExtent,duration:const Duration(milliseconds:180),curve:Curves.easeOut);});}
  Future<void> _connect() async {await sub?.cancel();sub=TabuRealtimeService.events.listen((e){if(!mounted)return;final rid=e.data['roomId']?.toString();if(rid!=null&&rid.isNotEmpty&&rid!=widget.roomId)return;final n=_stateFrom(e.data);if(n!=null){final before=_messages(state).length;setState((){state=n;loading=false;error=null;});if(_messages(n).length>before)_scrollSoon();}if(e.type=='connection:disconnected')setState(()=>error='Bağlantı yenileniyor...');});try{final j=await TabuRealtimeService.join(widget.roomId);if(!mounted)return;final n=_stateFrom(j);if(n==null)throw const ApiException('Tabu durumu alınamadı.');setState((){state=n;loading=false;error=null;});}on ApiException catch(e){try{final f=await TabuGameApiService.state(widget.roomId);if(!mounted)return;setState((){state=f;loading=false;error='Canlı bağlantı yeniden kuruluyor.';});Future.delayed(const Duration(seconds:2),(){if(mounted)_connect();});}catch(_){if(mounted)setState((){loading=false;error=e.message;});}}}
  Future<void> _send() async {final t=input.text.trim();if(t.isEmpty||sending||state?['phase']!='play')return;setState(()=>sending=true);try{final r=state?['isNarrator']==true?await TabuRealtimeService.speakerMessage(widget.roomId,t):await TabuRealtimeService.guess(widget.roomId,t);final n=_stateFrom(r);if(!mounted)return;input.clear();if(n!=null)setState(()=>state=n);_scrollSoon();}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}finally{if(mounted)setState(()=>sending=false);}}
  Future<void> _skip() async {if(sending||state?['isNarrator']!=true||state?['phase']!='play')return;setState(()=>sending=true);try{final r=await TabuRealtimeService.skip(widget.roomId);final n=_stateFrom(r);if(mounted&&n!=null)setState(()=>state=n);}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}finally{if(mounted)setState(()=>sending=false);}}
  Widget _avatar(Map<String,dynamic>p,{double radius=24,bool ring=false}){final name=p['name']?.toString()??'Oyuncu',photo=_photo(p);return Container(width:radius*2+6,height:radius*2+6,padding:EdgeInsets.all(ring?3:0),decoration:BoxDecoration(shape:BoxShape.circle,border:ring?Border.all(color:lime,width:3):null),child:ClipOval(child:photo.isEmpty?Container(color:surface2,alignment:Alignment.center,child:Text(name.isEmpty?'?':name[0].toUpperCase(),style:TextStyle(color:ink,fontWeight:FontWeight.w900))):Image.network(photo,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(color:surface2,alignment:Alignment.center,child:Icon(Icons.person,color:ink)))));}
  Widget _header(){final i=(state?['narratorIndex'] as num?)?.toInt()??0,total=(state?['totalNarrators'] as num?)?.toInt()??6,s=_secondsLeft('turnEndsAt');return Padding(padding:const EdgeInsets.fromLTRB(16,8,16,4),child:Row(children:[SizedBox(width:42,height:42,child:IconButton(onPressed:()=>Navigator.pop(context),style:IconButton.styleFrom(backgroundColor:surface),icon:Icon(Icons.arrow_back_rounded,color:ink))),const SizedBox(width:10),const Meet6MiniBrand(height:23,forceLogo2:true),const SizedBox(width:7),Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:5),decoration:BoxDecoration(color:dark?lime:navy,borderRadius:BorderRadius.circular(16)),child:Text('TABU',style:TextStyle(color:dark?navy:lime,fontWeight:FontWeight.w900,fontSize:11))),const Spacer(),Text('${i+1}/$total',style:TextStyle(color:ink,fontSize:13,fontWeight:FontWeight.w900)),const SizedBox(width:10),SizedBox(width:46,height:46,child:Stack(alignment:Alignment.center,children:[SizedBox(width:46,height:46,child:CircularProgressIndicator(value:(s/60).clamp(0,1),strokeWidth:5,backgroundColor:line,valueColor:const AlwaysStoppedAnimation(lime))),Text('$s',style:TextStyle(color:ink,fontSize:14,fontWeight:FontWeight.w900))]))]));}
  Widget _players(){final ps=_maps(state?['players']),nid=state?['narratorUserId']?.toString(),me=widget.profileName.trim();final gv=state?['isNarrator']!=true;return SizedBox(height:88,child:ListView.separated(scrollDirection:Axis.horizontal,padding:const EdgeInsets.fromLTRB(16,4,16,4),itemCount:ps.length,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(_,i){final p=ps[i],n=p['name']?.toString()??'Oyuncu',isN=p['id']?.toString()==nid,isMe=me.isNotEmpty&&n.trim()==me;return SizedBox(width:60,child:Column(children:[_avatar(p,radius:22,ring:gv?isMe:isN),const SizedBox(height:2),Text(n,maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(color:ink,fontSize:10.5,fontWeight:FontWeight.w900)),if(gv&&isN)const Text('Anlatıyor',style:TextStyle(color:Color(0xFF6F8DFF),fontSize:8.5,fontWeight:FontWeight.w900))]));}));}
  Widget _narratorCard(){final target=state?['target']?.toString()??'';final f=state?['forbidden'] is List?(state!['forbidden'] as List).map((e)=>e.toString()).toList():<String>[];return Container(margin:const EdgeInsets.fromLTRB(14,2,14,6),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:dark?const Color(0xFF172338):navy,borderRadius:BorderRadius.circular(22),border:dark?Border.all(color:const Color(0xFF29364D)):null),child:Column(mainAxisSize:MainAxisSize.min,children:[Row(children:[Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:4),decoration:BoxDecoration(color:lime,borderRadius:BorderRadius.circular(14)),child:const Text('ANLAT',style:TextStyle(color:navy,fontSize:10,fontWeight:FontWeight.w900))),const SizedBox(width:10),Expanded(child:Text(target,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white,fontSize:27,fontWeight:FontWeight.w900)))]),const SizedBox(height:9),Align(alignment:Alignment.centerLeft,child:Wrap(spacing:6,runSpacing:6,children:f.map((w)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:5),decoration:BoxDecoration(color:coral,borderRadius:BorderRadius.circular(16)),child:Text(w,style:const TextStyle(color:Colors.white,fontSize:10.5,fontWeight:FontWeight.w900)))).toList()))]));}
  Widget _guesserCard(){final n=state?['narratorName']?.toString()??'Anlatıcı';return Container(margin:const EdgeInsets.fromLTRB(14,2,14,6),padding:const EdgeInsets.symmetric(horizontal:14,vertical:9),decoration:BoxDecoration(color:dark?const Color(0xFF172338):const Color(0xFFEFFFAC),borderRadius:BorderRadius.circular(20),border:dark?Border.all(color:const Color(0xFF2C3A52)):null),child:Row(children:[Container(width:38,height:38,decoration:BoxDecoration(color:dark?lime:navy,shape:BoxShape.circle),child:Icon(Icons.campaign_rounded,color:dark?navy:lime,size:24)),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[Text('$n anlatıyor',style:TextStyle(color:ink,fontSize:16,fontWeight:FontWeight.w900)),const SizedBox(height:2),Text('Tahminini mesaj alanına yaz.',style:TextStyle(color:muted,fontSize:11.5,fontWeight:FontWeight.w700))]))]));}
  Widget _feed(){final ms=_messages(state),ps=_maps(state?['players']);Map<String,dynamic>? byId(String id){for(final p in ps){if(p['id']?.toString()==id)return p;}return null;}return ListView.builder(controller:scroll,padding:const EdgeInsets.fromLTRB(16,6,16,10),itemCount:ms.length,itemBuilder:(_,i){final m=ms[i],nm=m['role']=='narrator',uid=m['userId']?.toString()??m['senderUserId']?.toString()??'';final p=byId(uid)??{'name':m['name']?.toString()??'Oyuncu'},name=m['name']?.toString()??p['name']?.toString()??'Oyuncu';return Padding(padding:const EdgeInsets.only(bottom:9),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[_avatar(p,radius:18),const SizedBox(width:8),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(nm?'$name · anlatıcı':name,style:TextStyle(color:nm?const Color(0xFF6F9DFF):ink,fontSize:11.5,fontWeight:FontWeight.w900)),const SizedBox(height:3),Container(width:double.infinity,padding:const EdgeInsets.symmetric(horizontal:12,vertical:9),decoration:BoxDecoration(color:nm?(dark?const Color(0xFF172A4A):const Color(0xFFE9EFFF)):surface2,borderRadius:BorderRadius.circular(14),border:dark?Border.all(color:line):null),child:Text(m['text']?.toString()??'',style:TextStyle(color:ink,fontSize:14.5,height:1.35,fontWeight:FontWeight.w600))) ]))]));});}
  Widget _composer(){final narrator=state?['isNarrator']==true,enabled=state?['phase']=='play'&&!sending;return SafeArea(top:false,child:Container(padding:const EdgeInsets.fromLTRB(12,7,12,7),decoration:BoxDecoration(color:surface,border:Border(top:BorderSide(color:line))),child:Row(children:[if(narrator)...[SizedBox(height:46,child:OutlinedButton(onPressed:enabled?_skip:null,child:const Text('Pas',style:TextStyle(fontWeight:FontWeight.w900)))),const SizedBox(width:8)],Expanded(child:SizedBox(height:46,child:TextField(controller:input,enabled:enabled,textInputAction:TextInputAction.send,onSubmitted:(_)=>_send(),maxLength:narrator?200:80,style:TextStyle(color:ink,fontSize:14,fontWeight:FontWeight.w700),decoration:InputDecoration(counterText:'',hintText:narrator?'Kelimeyi anlat...':'Tahminini yaz...',hintStyle:TextStyle(color:muted),filled:true,fillColor:surface2,contentPadding:const EdgeInsets.symmetric(horizontal:14),border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide(color:line)),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide(color:line)),focusedBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:const BorderSide(color:lime)))))),const SizedBox(width:8),SizedBox(width:46,height:46,child:IconButton.filled(onPressed:enabled?_send:null,style:IconButton.styleFrom(backgroundColor:lime,foregroundColor:navy),icon:sending?const SizedBox(width:16,height:16,child:CircularProgressIndicator(strokeWidth:2,color:navy)):const Icon(Icons.send_rounded)))])));}
  Widget _resultOverlay(){final r=state?['lastResult'] is Map?Map<String,dynamic>.from(state!['lastResult']):<String,dynamic>{};final k=r['kind']?.toString()??'';final title=k=='tabu'?'TABU!':k=='pass'?'Pas geçildi!':'Doğru tahmin!';final subtitle=k=='tabu'?'Yasaklı kelime kullanıldı. Sıradaki anlatıcı geliyor.':k=='pass'?'Aynı anlatıcı için yeni kelime geliyor.':'Yeni kelime hazırlanıyor.';final c=k=='tabu'?coral:k=='pass'?const Color(0xFF8792A8):const Color(0xFF42C957);return Stack(children:[Positioned.fill(child:Container(color:const Color(0xFF020713).withOpacity(.72))),Center(child:Container(width:340,margin:const EdgeInsets.all(24),padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:surface,borderRadius:BorderRadius.circular(28),border:dark?Border.all(color:line):null),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(k=='tabu'?Icons.block_rounded:k=='pass'?Icons.skip_next_rounded:Icons.check_rounded,color:c,size:54),const SizedBox(height:14),Text(title,style:TextStyle(color:ink,fontSize:27,fontWeight:FontWeight.w900)),const SizedBox(height:7),Text(subtitle,textAlign:TextAlign.center,style:TextStyle(color:muted,fontSize:14,height:1.35,fontWeight:FontWeight.w700)),if(k=='tabu')...[const SizedBox(height:10),Text(r['forbiddenWord']?.toString()??'',style:const TextStyle(color:coral,fontSize:16,fontWeight:FontWeight.w900))],const SizedBox(height:18),Container(height:46,padding:const EdgeInsets.symmetric(horizontal:16),decoration:BoxDecoration(color:lime,borderRadius:BorderRadius.circular(23)),child:Row(children:[const Expanded(child:Text('Devam ediyor...',style:TextStyle(color:navy,fontWeight:FontWeight.w900))),Text('${_secondsLeft('phaseEndsAt')} sn',style:const TextStyle(color:navy,fontWeight:FontWeight.w900))]))])))]);}
  Widget _turnResult(){final t=state?['currentTurn'] is Map?Map<String,dynamic>.from(state!['currentTurn']):<String,dynamic>{};return Center(child:Container(margin:const EdgeInsets.all(24),padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:surface,borderRadius:BorderRadius.circular(28),border:Border.all(color:line)),child:Column(mainAxisSize:MainAxisSize.min,children:[Text('${state?['narratorName']??'Anlatıcı'}’nun turu bitti',textAlign:TextAlign.center,style:TextStyle(color:ink,fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:14),Text('${t['correct']??0} doğru · ${t['tabu']??0} tabu · ${t['pass']??0} pas',style:const TextStyle(color:lime,fontWeight:FontWeight.w900)),const SizedBox(height:8),Text('${_secondsLeft('phaseEndsAt')} sn sonra sıradaki anlatıcı',style:TextStyle(color:muted,fontSize:11,fontWeight:FontWeight.w700))])));}
  Widget _play()=>Column(children:[_header(),_players(),if(error!=null)Text(error!,style:const TextStyle(color:coral,fontSize:10)),state?['isNarrator']==true?_narratorCard():_guesserCard(),Expanded(child:_feed()),_composer()]);
  @override Widget build(BuildContext context){if(loading)return Scaffold(backgroundColor:page,body:const Center(child:CircularProgressIndicator(color:lime)));final phase=state?['phase']?.toString()??'play';if(phase=='final')return Scaffold(backgroundColor:page,body:SafeArea(child:Column(children:[_header(),Expanded(child:Center(child:Text('Tabu sonucu',style:TextStyle(color:ink,fontSize:34,fontWeight:FontWeight.w900))))])));return Scaffold(resizeToAvoidBottomInset:true,backgroundColor:page,body:SafeArea(child:phase=='word_result'?Stack(children:[Positioned.fill(child:_play()),Positioned.fill(child:_resultOverlay())]):phase=='turn_result'?Column(children:[_header(),_players(),Expanded(child:_turnResult())]):_play()));}
}
