-- Red Flag / Green Flag question pack v1 imported from meet6_red_flag_green_flag_questions.json
-- Source fields: id, text, level, enabled. Categories are assigned for balanced live rotation.
-- Political prompts are retained only as disabled/unsafe audit records and can never be selected.

insert into red_flag_questions(prompt, category, difficulty, active, admin_approved)
values
('Mesajlara 8 saat sonra dönmek', 'messaging', 'light', true, true),
('İlk buluşmada sürekli telefona bakmak', 'first_date', 'medium', true, true),
('Eski sevgiliyle yakın arkadaş kalmak', 'relationship', 'debate', true, true),
('İlk buluşmada geç kalıp haber vermemek', 'first_date', 'medium', true, true),
('Partnerinin şifresini bilmek istemek', 'boundaries', 'debate', true, true),
('Her gün mutlaka mesajlaşmak istemek', 'messaging', 'light', true, true),
('İlk buluşmada hesabı paylaşmak istemek', 'first_date', 'light', true, true),
('Sosyal medyada ilişkiyi gizlemek istemek', 'social_media', 'medium', true, true),
('Her tartışmada sessiz kalmak', 'daily_habits', 'medium', true, true),
('Kıskançlığı sevgi göstergesi saymak', 'jealousy', 'debate', true, true),
('İlk buluşmada çok kişisel sorular sormak', 'first_date', 'medium', true, true),
('Mesajı görüp cevap vermemek', 'messaging', 'light', true, true),
('Eski ilişkilerden sürekli bahsetmek', 'relationship', 'medium', true, true),
('Partnerinin arkadaşlarını sevmemek', 'relationship', 'medium', true, true),
('Her planı son anda iptal etmek', 'daily_habits', 'medium', true, true),
('İlk buluşmaya arkadaş getirmek', 'first_date', 'light', true, true),
('Çok sık konum istemek', 'boundaries', 'debate', true, true),
('Partnerinin telefonunu kontrol etmek', 'boundaries', 'debate', true, true),
('Her tartışmada ayrılıkla tehdit etmek', 'relationship', 'debate', true, true),
('Özür dilemekte zorlanmak', 'relationship', 'medium', true, true),
('Her şeyi sosyal medyada paylaşmak', 'social_media', 'light', true, true),
('Hiç fotoğraf paylaşmak istememek', 'daily_habits', 'light', true, true),
('Çok hızlı “seni seviyorum” demek', 'relationship', 'medium', true, true),
('İlk haftada ciddi ilişki konuşmak', 'relationship', 'medium', true, true),
('Partnerinin giyimine karışmak', 'boundaries', 'debate', true, true),
('Karşı tarafın arkadaş çevresine karışmak', 'boundaries', 'debate', true, true),
('Sürekli eski mesajları gündeme getirmek', 'messaging', 'medium', true, true),
('Tartışınca günlerce konuşmamak', 'daily_habits', 'debate', true, true),
('İlk buluşmada sarılmak istemek', 'first_date', 'light', true, true),
('İlk buluşmada öpüşmek istemek', 'first_date', 'medium', true, true),
('Çok fazla emoji kullanmak', 'daily_habits', 'light', true, true),
('Mesajlarda çok kısa cevap vermek', 'messaging', 'light', true, true),
('Her mesajı anında cevaplamak', 'messaging', 'light', true, true),
('Günde sadece bir kez yazmak', 'daily_habits', 'light', true, true),
('“Nasılsın?” dışında konu açmamak', 'daily_habits', 'light', true, true),
('Tanışır tanışmaz sesli aramak', 'messaging', 'light', true, true),
('Görüntülü konuşmayı sevmemek', 'messaging', 'light', true, true),
('İlk buluşmada fotoğraf çekmek istemek', 'first_date', 'light', true, true),
('Partnerinin sosyal medya takipçilerine karışmak', 'social_media', 'debate', true, true),
('Eski fotoğrafları silmesini istemek', 'daily_habits', 'debate', true, true),
('Partnerinin eski sevgilisini stalklamak', 'social_media', 'medium', true, true),
('Kıskandırmak için story atmak', 'social_media', 'medium', true, true),
('Tartışırken ekran görüntüsü almak', 'daily_habits', 'medium', true, true),
('Özel mesajları arkadaşlara göstermek', 'messaging', 'debate', true, true),
('Sürekli “neredesin?” diye sormak', 'daily_habits', 'debate', true, true),
('Her hafta mutlaka görüşmek istemek', 'daily_habits', 'light', true, true),
('Çok bağımsız olmak', 'daily_habits', 'light', true, true),
('Her şeyi birlikte yapmak istemek', 'daily_habits', 'medium', true, true),
('Ayrı arkadaş çevrelerinin olmasını istemek', 'friendship', 'light', true, true),
('Partnerinin yalnız zaman istemesine alınmak', 'relationship', 'medium', true, true),
('İlk buluşmada aileden bahsetmek', 'first_date', 'light', true, true),
('İlk buluşmada evlilikten bahsetmek', 'first_date', 'medium', true, true),
('Çocuk isteyip istemediğini erken sormak', 'relationship', 'medium', true, true),
('Maddi durumu ilk günlerde sormak', 'daily_habits', 'medium', true, true),
('Mesleğini çok önemsemek', 'daily_habits', 'medium', true, true),
('Boy-kilo gibi fiziksel özellikleri sormak', 'daily_habits', 'medium', true, true),
('Burçlara göre ilişki değerlendirmek', 'relationship', 'light', true, true),
('Partnerinin burcuna göre karar vermek', 'relationship', 'light', true, true),
('İlk buluşmada alkol almak istemek', 'first_date', 'medium', true, true),
('Sigara içmesini sorun etmek', 'daily_habits', 'medium', true, true),
('Çok farklı müzik zevklerine sahip olmak', 'daily_habits', 'light', true, true),
('Çok farklı siyasi görüşlere sahip olmak', 'daily_habits', 'debate', false, false),
('Çok farklı yaşam tarzlarına sahip olmak', 'daily_habits', 'medium', true, true),
('Farklı şehirlerde yaşamak', 'daily_habits', 'medium', true, true),
('Uzak mesafe ilişkiye açık olmak', 'relationship', 'medium', true, true),
('Her gece görüntülü konuşmak istemek', 'messaging', 'medium', true, true),
('Sabah mesajı beklemek', 'messaging', 'light', true, true),
('İyi geceler mesajı gelmeyince alınmak', 'messaging', 'light', true, true),
('Doğum gününü çok önemsemek', 'daily_habits', 'light', true, true),
('Yıldönümlerini unutmak', 'daily_habits', 'medium', true, true),
('Hediye almaya çok önem vermek', 'daily_habits', 'light', true, true),
('Pahalı hediye beklemek', 'daily_habits', 'medium', true, true),
('Sürprizleri sevmemek', 'daily_habits', 'light', true, true),
('Her şeyi planlı yapmak istemek', 'daily_habits', 'light', true, true),
('Anlık planları sevmek', 'daily_habits', 'light', true, true),
('İlk buluşmada çok suskun olmak', 'first_date', 'light', true, true),
('Sürekli konuşmak', 'daily_habits', 'light', true, true),
('Karşı tarafın sözünü sık sık kesmek', 'daily_habits', 'medium', true, true),
('Çok yüksek sesle konuşmak', 'daily_habits', 'light', true, true),
('Garsona kaba davranmak', 'daily_habits', 'medium', true, true),
('Sürekli şikâyet etmek', 'daily_habits', 'medium', true, true),
('Her konuda negatif olmak', 'daily_habits', 'medium', true, true),
('Kendinden sürekli bahsetmek', 'daily_habits', 'medium', true, true),
('Karşı tarafa hiç soru sormamak', 'daily_habits', 'medium', true, true),
('İlk buluşmada eski sevgiliyi kötülemek', 'first_date', 'medium', true, true),
('Arkadaşları hakkında kötü konuşmak', 'friendship', 'medium', true, true),
('Ailesiyle çok fazla iç içe olmak', 'friendship', 'medium', true, true),
('Ailesinin fikrine çok önem vermek', 'friendship', 'medium', true, true),
('Partnerini ailesiyle hemen tanıştırmak istemek', 'relationship', 'medium', true, true),
('İlişkiyi çok yavaş ilerletmek istemek', 'relationship', 'light', true, true),
('İlişkiyi çok hızlı ilerletmek istemek', 'relationship', 'medium', true, true),
('“Ben buyum, değişmem” demek', 'daily_habits', 'medium', true, true),
('Tartışmada haklı çıkmaya odaklanmak', 'relationship', 'medium', true, true),
('Hata yaptığında konuyu değiştirmek', 'relationship', 'medium', true, true),
('Partnerinin hobileriyle dalga geçmek', 'relationship', 'medium', true, true),
('Partnerinin başarılarını küçümsemek', 'relationship', 'debate', true, true),
('Arkadaşlarıyla flörtöz konuşmak', 'friendship', 'debate', true, true),
('Başkalarının fotoğraflarına sürekli yorum yapmak', 'social_media', 'medium', true, true),
('Flört uygulamasını eşleşmeden sonra silmemek', 'social_media', 'debate', true, true),
('“Ben kıskanç değilim” deyip sürekli kontrol etmek', 'jealousy', 'debate', true, true)
on conflict(prompt) do update set
  category=excluded.category,
  difficulty=excluded.difficulty,
  active=excluded.active,
  admin_approved=excluded.admin_approved,
  safe=true,
  updated_at=now();

update red_flag_questions
set active=false, admin_approved=false, safe=false, updated_at=now()
where lower(prompt) like '%siyasi%';
